// This file was generated by img2gb, DO NOT EDIT

#ifndef _HUD_TILEMAP_H
#define _HUD_TILEMAP_H

extern const UINT8 KEYOP_TILEMAP[];
#define KEYOP_TILEMAP_WIDTH 20
#define KEYOP_TILEMAP_HEIGHT 2


#endif
