// This file was generated by img2gb, DO NOT EDIT

#ifndef _PUZZLE_MOEGI_TILESET_H
#define _PUZZLE_MOEGI_TILESET_H

#include <gbdk/platform.h>

extern const UINT8 PUZZLE_MOEGI_TILESET[];
#define PUZZLE_MOEGI_TILESET_TILE_COUNT 170

BANKREF_EXTERN(PUZZLE_MOEGI_TILESET)

#endif
