// This file was generated by img2gb, DO NOT EDIT

#ifndef _PUZZLE_STRIPES_TILESET_H
#define _PUZZLE_STRIPES_TILESET_H

extern const UINT8 PUZZLE_STRIPES_TILESET[];
#define PUZZLE_STRIPES_TILESET_TILE_COUNT 6


#endif
