// This file was generated by img2gb, DO NOT EDIT

#ifndef _PUZZLE_BORDER_TILESET_H
#define _PUZZLE_BORDER_TILESET_H

extern const UINT8 PUZZLE_BORDER_TILESET[];
#define PUZZLE_BORDER_TILESET_TILE_COUNT 4


#endif
