// This file was generated by img2gb, DO NOT EDIT

#ifndef _PUZZLE_HI_TILESET_H
#define _PUZZLE_HI_TILESET_H

extern const UINT8 PUZZLE_HI_TILESET[];
#define PUZZLE_HI_TILESET_TILE_COUNT 191


#endif
