// This file was generated by img2gb, DO NOT EDIT

#ifndef _PUZZLE_NICE_TILESET_H
#define _PUZZLE_NICE_TILESET_H

#include <gbdk/platform.h>

extern const UINT8 PUZZLE_NICE_TILESET[];
#define PUZZLE_NICE_TILESET_TILE_COUNT 202

BANKREF_EXTERN(PUZZLE_NICE_TILESET)

#endif
