// This file was generated by img2gb, DO NOT EDIT

#ifndef _PUZZLE_KEYOP_TILEMAP_H
#define _PUZZLE_KEYOP_TILEMAP_H

extern const UINT8 PUZZLE_KEYOP_TILEMAP[];
#define PUZZLE_KEYOP_TILEMAP_WIDTH 20
#define PUZZLE_KEYOP_TILEMAP_HEIGHT 2


#endif
