// This file was generated by img2gb, DO NOT EDIT

#ifndef _PUZZLE_PUIPUI_TILESET_H
#define _PUZZLE_PUIPUI_TILESET_H

#include <gbdk/platform.h>

extern const UINT8 PUZZLE_PUIPUI_TILESET[];
#define PUZZLE_PUIPUI_TILESET_TILE_COUNT 183

BANKREF_EXTERN(PUZZLE_PUIPUI_TILESET)

#endif
