// This file was generated by img2gb, DO NOT EDIT

#ifndef _PUZZLE_KYURUN_TILESET_H
#define _PUZZLE_KYURUN_TILESET_H

#include <gbdk/platform.h>

extern const UINT8 PUZZLE_KYURUN_TILESET[];
#define PUZZLE_KYURUN_TILESET_TILE_COUNT 198

BANKREF_EXTERN(PUZZLE_KYURUN_TILESET)

#endif
