// This file was generated by img2gb, DO NOT EDIT

#ifndef _PUZZLE_NYAN_TILESET_H
#define _PUZZLE_NYAN_TILESET_H

#include <gbdk/platform.h>

extern const UINT8 PUZZLE_NYAN_TILESET[];
#define PUZZLE_NYAN_TILESET_TILE_COUNT 191

BANKREF_EXTERN(PUZZLE_NYAN_TILESET)

#endif
