// This file was generated by img2gb, DO NOT EDIT

#ifndef _PUZZLE_NICE_TILEMAP_H
#define _PUZZLE_NICE_TILEMAP_H

extern const UINT8 PUZZLE_NICE_TILEMAP[];
#define PUZZLE_NICE_TILEMAP_WIDTH 16
#define PUZZLE_NICE_TILEMAP_HEIGHT 14


#endif
