// This file was generated by img2gb, DO NOT EDIT

#ifndef _PENLIGHT_TILEMAP_H
#define _PENLIGHT_TILEMAP_H

extern const UINT8 STAGE_TILEMAP[];
#define STAGE_TILEMAP_WIDTH 20
#define STAGE_TILEMAP_HEIGHT 18


#endif
