// This file was generated by img2gb, DO NOT EDIT

#ifndef _TITLE_TILESET_H
#define _TITLE_TILESET_H

#include <gbdk/platform.h>

extern const UINT8 TITLE_TILESET[];
#define TITLE_TILESET_TILE_COUNT 178

BANKREF_EXTERN(TITLE_TILESET)

#endif
