// This file was generated by img2gb, DO NOT EDIT

#ifndef _TITLE_TILEMAP_H
#define _TITLE_TILEMAP_H

extern const UINT8 TITLE_TILEMAP[];
#define TITLE_TILEMAP_WIDTH 20
#define TITLE_TILEMAP_HEIGHT 18


#endif
